# frozen_string_literal: true

module RubyLLM
  module Test
    module Errors
      # # No Response Provided Error
      #
      # If the test setup does not provide a response for a test chat completion,
      # this error is raised to indicate that the test is incomplete. The final chat message,
      # generated by the `ask` method, is included in the error message for context.
      class NoResponseProvidedError < StandardError
        attr_reader :messages

        def initialize(messages)
          @messages = messages

          super("No test response provided for the following request:\n#{messages.last.content}")
        end
      end
    end
  end
end
